FROM node:18.15.0
LABEL org.opencontainers.image.source https://github.com/alvarorg14/Mower_Control_API
COPY . /app
WORKDIR /app

# Install dependencies
RUN npm install

ARG MYSQL_HOST="localhost"
ENV MYSQL_HOST=$MYSQL_HOST

ARG MYSQL_USER="root"
ENV MYSQL_USER=$MYSQL_USER

ARG MYSQL_PASSWORD="password"
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD

ARG MYSQL_DATABASE="mowercontrol"
ENV MYSQL_DATABASE=$MYSQL_DATABASE

ARG MYSQL_ROOT_PASSWORD="password"
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

ARG MYSQL_PORT="33060"
ENV MYSQL_PORT=$MYSQL_PORT

ARG HUSQVARNA_CLIENT_ID="client_id"
ENV HUSQVARNA_CLIENT_ID=$HUSQVARNA_CLIENT_ID

ARG HUSQVANRA_OAUTH_URL="https://api.authentication.husqvarnagroup.dev/v1/oauth2/token"
ENV HUSQVANRA_OAUTH_URL=$HUSQVANRA_OAUTH_URL

ARG HUSQVARNA_API_URL="https://api.amc.husqvarna.dev/v1"
ENV HUSQVARNA_API_URL=$HUSQVARNA_API_URL

ARG JWT_SECRET="secret"
ENV JWT_SECRET=$JWT_SECRET

ARG JWT_TOKEN_EXPIRATION="90d"
ENV JWT_TOKEN_EXPIRATION=$JWT_TOKEN_EXPIRATION

# Run the app
CMD ["npm", "start"]


