name: Codecov

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test REST API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: npm install
    - name: Run tests and collect coverage
      run: npm test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
